/*globals define, WebGMEGlobal*/

/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue Sep 24 2019 01:13:00 GMT-0500 (Central Daylight Time).
 */

define(['css!./styles/ViewNotebookWidget.css'], function () {
    'use strict';

    var WIDGET_CLASS = 'view-notebook';

    function ViewNotebookWidget(logger, container) {
        this._logger = logger.fork('Widget');

        this._el = container;

        this._initialize();

        this._logger.debug('ctor finished');
    }

    ViewNotebookWidget.prototype._initialize = function () {

        // set widget class
        this._el.addClass(WIDGET_CLASS);

        // Create a dummy header
        this._el.append('<h3>Waiting connection to Jupyter server...</h3>');

        this.notebookIframe = null;
    };

    ViewNotebookWidget.prototype.onWidgetContainerResize = function (width, height) {
        this._logger.debug('Widget is resizing...');
    };

    ViewNotebookWidget.prototype.viewNotebookOfNode = function(ipynb){
        var notebookIframe = document.createElement('iframe');
        notebookIframe.name = "notebook";
        notebookIframe.style.height = "100%";
        notebookIframe.style.width = "100%";
        notebookIframe.src = '/jupyter/notebooks/' + ipynb + '.ipynb';
        
        $(this._el).empty();
        if(ipynb){
            this._el.append(notebookIframe);
            this.notebookIframe = notebookIframe;
        } else {
            this.notebookIframe = null;
            this._el.append('<h2>Notebook have not been assigned to graph!</h2>');
            this._el.append('<h3>Use plugin to generate notebook first!</h3>');
        }

    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    ViewNotebookWidget.prototype.destroy = function () {
    };

    ViewNotebookWidget.prototype.onActivate = function () {
        this._logger.debug('ViewNotebookWidget has been activated');
    };

    ViewNotebookWidget.prototype.onDeactivate = function () {
        this._logger.debug('ViewNotebookWidget has been deactivated');
    };

    return ViewNotebookWidget;
});
