/*globals define, WebGMEGlobal*/
/**
 * Generated by VisualizerGenerator 1.7.0 from webgme on Tue Sep 24 2019 01:13:00 GMT-0500 (Central Daylight Time).
 */

define([
    'js/Constants',
    'js/Utils/GMEConcepts',
    'js/NodePropertyNames'
], function (
    CONSTANTS,
    GMEConcepts,
    nodePropertyNames
) {

    'use strict';

    function ViewNotebookControl(options) {
        var self = this;

        this._logger = options.logger.fork('Control');

        this._client = options.client;

        // Initialize core collections and variables
        this._widget = options.widget;

        this._currentNodeId = null;
        this._currentNodeParentId = undefined;

        this._logger.debug('ctor finished');

        self._territoryId = self._client.addUI(self, function (events) {
            self._eventCallback(events);
        });
    }

    /* * * * * * * * Visualizer content update callbacks * * * * * * * */
    // One major concept here is with managing the territory. The territory
    // defines the parts of the project that the visualizer is interested in
    // (this allows the browser to then only load those relevant parts).
    ViewNotebookControl.prototype.selectedObjectChanged = function (nodeId) {
        if(nodeId !== null && nodeId !== this._currentNodeId){
            this._currentNodeId = nodeId;
            this._selfPatterns = {};
            this._selfPatterns[nodeId] = {children: 0};
            this._client.updateTerritory(this._territoryId, this._selfPatterns);
        }
    };

    /* * * * * * * * Node Event Handling * * * * * * * */
    ViewNotebookControl.prototype._eventCallback = function (events) {
        var i = events ? events.length : 0,
            event,
            node;

        while (i--) {
            event = events[i];
            switch (event.etype) {

            case CONSTANTS.TERRITORY_EVENT_LOAD:
            case CONSTANTS.TERRITORY_EVENT_UPDATE:
                if(event.eid === this._currentNodeId){
                    node = this._client.getNode(this._currentNodeId);
                    if(node){
                        this._widget.viewNotebookOfNode(node.getAttribute('ipynb'));
                    }
                }
                break;
            //case CONSTANTS.TERRITORY_EVENT_UNLOAD:
            //    break;
            default:
                break;
            }
        }

        this._logger.debug('_eventCallback \'' + events.length + '\' items - DONE');
    };

    ViewNotebookControl.prototype._stateActiveObjectChanged = function (model, activeObjectId) {
        if (this._currentNodeId === activeObjectId) {
            // The same node selected as before - do not trigger
        } else {
            this.selectedObjectChanged(activeObjectId);
        }
    };

    /* * * * * * * * Visualizer life cycle callbacks * * * * * * * */
    ViewNotebookControl.prototype.destroy = function () {
        this._detachClientEventListeners();
        this._removeToolbarItems();
    };

    ViewNotebookControl.prototype._attachClientEventListeners = function () {
        this._detachClientEventListeners();
        WebGMEGlobal.State.on('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged, this);
    };

    ViewNotebookControl.prototype._detachClientEventListeners = function () {
        WebGMEGlobal.State.off('change:' + CONSTANTS.STATE_ACTIVE_OBJECT, this._stateActiveObjectChanged);
    };

    ViewNotebookControl.prototype.onActivate = function () {
        this._attachClientEventListeners();
        this._displayToolbarItems();

        if (typeof this._currentNodeId === 'string') {
            WebGMEGlobal.State.registerActiveObject(this._currentNodeId, {suppressVisualizerFromNode: true});
        }
    };

    ViewNotebookControl.prototype.onDeactivate = function () {
        this._detachClientEventListeners();
        this._hideToolbarItems();
    };

    /* * * * * * * * * * Toolbar * * * * * * * * * */
    
    ViewNotebookControl.prototype._displayToolbarItems = function () {

        // if (this._toolbarInitialized === true) {
            // for (var i = this._toolbarItems.length; i--;) {
                // this._toolbarItems[i].show();
            // }
        // } else {
            // this._initializeToolbar();
        // }
    };

    ViewNotebookControl.prototype._hideToolbarItems = function () {

        // if (this._toolbarInitialized === true) {
            // for (var i = this._toolbarItems.length; i--;) {
                // this._toolbarItems[i].hide();
            // }
        // }
    };

    ViewNotebookControl.prototype._removeToolbarItems = function () {

        // if (this._toolbarInitialized === true) {
            // for (var i = this._toolbarItems.length; i--;) {
                // this._toolbarItems[i].destroy();
            // }
        // }
    };

    ViewNotebookControl.prototype._initializeToolbar = function () {
        // var self = this,
            // toolBar = WebGMEGlobal.Toolbar;

        // this._toolbarItems = [];

        // this._toolbarItems.push(toolBar.addSeparator());

        // this.$btnModelHierarchyUp = toolBar.addButton({
            // title: 'Go to parent',
            // icon: 'glyphicon glyphicon-circle-arrow-up',
            // clickFn: function () {
                // WebGMEGlobal.State.registerActiveObject(self._currentNodeParentId);
            // }
        // });
        // this._toolbarItems.push(this.$btnModelHierarchyUp);
        // this.$btnModelHierarchyUp.hide();


        // this.$cbShowConnection = toolBar.addCheckBox({
            // title: 'toggle checkbox',
            // icon: 'gme icon-gme_diagonal-arrow',
            // checkChangedFn: function (data, checked) {
                // self._logger.debug('Checkbox has been clicked!');
            // }
        // });
        // this._toolbarItems.push(this.$cbShowConnection);

        // this._toolbarInitialized = true;
    };

    return ViewNotebookControl;
});
