# To build and launch (first time):
#   $ docker-compose up -d
# To create new images (--no-cache) to force building from scratch:
#   $ docker-compose build
# To launch again (leave out -d for non daemon launch):
#   $ docker-compose up -d
# Short command for rebuilding and restarting
#   $ docker-compose up -d --build
# To stop containers:
#  $ docker-compose stop
# To clean up containers/images/networks:
#  $ docker system prune
version: '3'
networks:
  frontend:
    driver: bridge
  database:
    driver: bridge
  workers:
    internal: true
    driver: bridge
services:
  webgme-server:
    build:
      context: .
    depends_on:
    - mongo
    environment:
    - NODE_ENV=local
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - database
    - workers
    - frontend
    ports:
      - 8888:8888
  mongo:
    image: mongo:3.4.1
    expose:
    - 27017
    networks:
    - database
  #py-core-executor:
  #  build:
  #    context: .
  #    dockerfile: DockerfilePyCoreExecutor
  #  depends_on:
  #  - webgme-server
  #  networks:
  #  - workers
  #  environment:
  #  - NODE_ENV=docker
  #  command: ["cat", "/dev/null"] # A no-op command so the image is built.
  jupyter:
    build:
      context: .
      dockerfile: DockerfileJupyter
    networks:
      - frontend
      - workers
